myapp:
  who: GitHub configuration repository!!!!!
  password: letmein01

hello:
  message: Howdy do!

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: cloud

foo:
  bar: Profile test

