myapp:
  who: GitHub configuration repository!!!!!
  password: s3cr3t

hello:
  message: Hello\nWorld!!!

greeting:
  hello: Hello, UberConf!!!
  message: Yo

---
spring:
  profiles: local
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: cloud

foo:
  bar: Profile test

