myapp:
  who: GitHub configuration repository!!!!!
  password: s3cr3t

hello:
  message: Hello World!!!

greeting:
  hello: Hello, World!!!
  message: Hello, from branch dr-branch

dummy:
  property: some value tweaked
---
spring:
  profiles: local
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: cloud

foo:
  bar: Profile test
  
hello:
  message: Hello cloud (DEFAULT APP)
